---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "/home/vibhuti/ec2/myenv/bin/python"

  tasks:
    - name: create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "ansible"
        instance_type: t2.micro
        security_group: default
        region: "us-east-2"
        aws_access_key: "{{ec2_access_key}}"  # From vault as defined
        aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined
        network_interfaces:
          - assign_public_ip: true
        image_id: "{{ item.image }}"
        tags:
          Environment: "{{ item.name }}"
      loop:
        - { image: "ami-0b016c703b95ecbe4", name: "managed-node1" }
        - { image: "ami-0d1b5a8c13042c939", name: "managed-node2" }
        - { image: "ami-0d1b5a8c13042c939", name: "managed-node3" }
