---
- name: Installing Apache Server
  hosts: myhosts
  remote_user: ubuntu
  become: true

  tasks:
    - name: Apache2 has latest version
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Copy the html file to the location
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'                                                                                                                                
